## 1NN and random forest. Digits dataset.

In [24]:
import sklearn 
import numpy as np
#from sklearn.cross_validation import train_test_split
from sklearn.metrics import mean_squared_error
from matplotlib import pyplot as plt

In [12]:
X, y = sklearn.datasets.load_digits(return_X_y = True)

Train test split: first 75 % is train

In [22]:
L = int(round(len(y)*0.75))
X_tr = X[0:L,:]
y_tr = y[0:L]

X_ts = X[L:len(y),:]
y_ts = y[L:len(y)]

print len(y_tr) + len(y_ts)
print len(y)

1797
1797


In [63]:
def NN_1(X,y,train_action=True):
    N = len(y)
    y_pred  = []
    for i in range(N):
        dist_list = []
        # for j in [ n in range(N) if n <> i]:
        for j in range(N):
            #if(train_action)
            #  break
            dist_tmp = np.linalg.norm(X[i,:]- X[j,:])
            dist_list.append( np.array([dist_tmp,y[j]]))
        dist_list.sort()                     
        y_pred[i] = dist_list[0][1]     
    return(y_pred)                

In [64]:
y = NN_1(X_tr, y_tr)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [131]:
N = len(y)
y_pred  = []

In [132]:
i = 0
dist_list = []

In [143]:
y_tr[0:12]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1])

In [141]:
j = 7
dist_tmp = np.linalg.norm(X_tr[i,:]- X_tr[j,:])
dist_list.append( np.array([dist_tmp, y_tr[j]]))

In [142]:
dist_list

[array([ 59.55669568,   1.        ]),
 array([ 54.12947441,   2.        ]),
 array([ 47.57099957,   3.        ]),
 array([ 50.33885179,   4.        ]),
 array([ 43.9089968,   5.       ]),
 array([ 48.55924217,   6.        ])]

In [122]:
dist_list = np.array(dist_list)

In [162]:
dist_list1 = np.array(dist_list)

In [163]:
dist_list

[array([ 59.55669568,   1.        ]),
 array([ 54.12947441,   2.        ]),
 array([ 47.57099957,   3.        ]),
 array([ 50.33885179,   4.        ]),
 array([ 43.9089968,   5.       ]),
 array([ 48.55924217,   6.        ])]

In [168]:
dist_list1

array([[  1.        ,  59.55669568],
       [  2.        ,  54.12947441],
       [  3.        ,  47.57099957],
       [  4.        ,  50.33885179],
       [  5.        ,  43.9089968 ],
       [  6.        ,  48.55924217]])

In [169]:
#dist_list1.sort(reverse=False)
print dist_list1.sort()

None


In [55]:
j = 2
dist_tmp = np.linalg.norm(X_tr[i,:]- X_tr[j,:])
dist_list.append( np.array([dist_tmp, y[j]]))

In [61]:
dist_list[0][1]

1.0