### Transformer class. Mean target encoding. 
Кодирование категориальных признаков средним по целевой переменной на примере dataset mushrooms.

In [1]:
import pandas as pd 
import numpy as np
import signal

from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from collections import Counter

In [2]:
df = pd.read_csv('mushrooms.csv', header=None)
df.head()

0  1  2  3  4  5  6  7  8  9  ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [3]:
df.shape

(8124, 23)

In [4]:
X, y = np.array(df.loc[:,1:]), np.array(df.loc[:,0])

In [5]:
label_encoder = LabelEncoder()
y = np.equal(y,'p').astype(int)
for i in range(X.shape[1]):
    X[:,i] = label_encoder.fit_transform(X[:,i])

In [6]:
#X[0:20,2]
#df.loc[0:19, 3].values

In [74]:
LR_PARAMS_DICT = {}

def fit(X,y):
    cnt = Counter()
    for i in range(X.shape[1]):
        for j in range(np.max(X[:,i])+1):
            ind = (X[:,i] == j)
            if (np.sum(ind) > 0):
                val = np.mean(y[ind])
            else: 
                val = np.mean(y)
            cnt[(i,j)] = val
        
    return cnt    


def transform(X, cnt):
    X_new = np.copy(X)
    for i in range(X.shape[1]):
        for j in range(np.max(X[:,i])+1):
            ind = (X[:,i]==j)
            X_new[ind,i] = cnt[(i,j)]
    
    return X_new     

In [73]:
def fit(X, y):
    cnt = Counter()
    for i in range(X.shape[1]):
        for j in range(np.max(X[:, i])):
            indices = X[:, i] == j
            if np.sum(indices) > 0:
                val = y[indices].mean()
            else:
                val = y.mean()
            cnt[(i, j)] = val

    return cnt

def transform(X, cnt):
    X_new = np.copy(X)
    for i in range(X.shape[1]): 
        for j in range(np.max(X[:, i])):
            indices = X[:, i] == j
            if np.sum(indices) > 0:
                X_new[indices, i] = cnt[(i, j)]

    return X_new

In [75]:
A = fit(X,y)

In [76]:
np.max(X[:,0])

5

In [77]:
np.max(X[:,21])

6

In [78]:
np.unique(df.loc[:,22].values)

array(['d', 'g', 'l', 'm', 'p', 'u', 'w'], dtype=object)

In [79]:
pd.Series(X[:,0]).value_counts()

5    3656
2    3152
3     828
0     452
4      32
1       4
dtype: int64

In [55]:
A

Counter({(0, 0): 0.10619469026548672,
         (0, 1): 1.0,
         (0, 2): 0.4936548223350254,
         (0, 3): 0.7246376811594203,
         (0, 4): 0.0,
         (0, 5): 0.4671772428884026,
         (1, 0): 0.3275862068965517,
         (1, 1): 1.0,
         (1, 2): 0.5524256651017214,
         (1, 3): 0.5363748458692972,
         (2, 0): 0.7142857142857143,
         (2, 1): 0.2727272727272727,
         (2, 2): 0.584,
         (2, 3): 0.4391304347826087,
         (2, 4): 0.44658493870402804,
         (2, 5): 0.6111111111111112,
         (2, 6): 0.0,
         (2, 7): 0.0,
         (2, 8): 0.3076923076923077,
         (2, 9): 0.6268656716417911,
         (3, 0): 0.6933445661331087,
         (3, 1): 0.1848341232227488,
         (4, 0): 0.0,
         (4, 1): 1.0,
         (4, 2): 1.0,
         (4, 3): 0.0,
         (4, 4): 1.0,
         (4, 5): 0.034013605442176874,
         (4, 6): 1.0,
         (4, 7): 1.0,
         (4, 8): 1.0,
         (5, 0): 0.08571428571428572,
         (5, 1): 0.

In [81]:
#for i in range(X.shape[1]):
#    print( i, len(np.unique(X[:,i])))

In [82]:
B = transform(X, A)

In [86]:
X[:10,0]

array([5, 5, 0, 5, 5, 5, 0, 0, 5, 0], dtype=object)

In [87]:
B[:10,0]

array([0.4671772428884026, 0.4671772428884026, 0.10619469026548672,
       0.4671772428884026, 0.4671772428884026, 0.4671772428884026,
       0.10619469026548672, 0.10619469026548672, 0.4671772428884026,
       0.10619469026548672], dtype=object)

In [11]:
np.unique(B[:1])

array([0, 0.22857142857142856, 0.29675425038639874, 0.31118314424635335,
       0.38321167883211676, 0.3835125448028674, 0.49318525996971224,
       0.5085470085470085, 0.540386803185438, 0.5524256651017214,
       0.5584263065179096, 0.7391304347826086, 1, 4, 5], dtype=object)

In [12]:
np.unique(df.loc[:,2].values)

array(['f', 'g', 's', 'y'], dtype=object)

In [13]:
np.unique(X[:,2])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=object)

In [24]:
df[2].value_counts()

y    3244
s    2556
f    2320
g       4
Name: 2, dtype: int64

In [40]:
X.shape

(8124, 22)

In [48]:
i = 0
j = 0
ind = (X[:,i] == j)

In [49]:
ind

array([False, False,  True, ..., False, False, False])

In [25]:
X[:,0]

array([5, 5, 0, ..., 2, 3, 5], dtype=object)

In [26]:
X.shape

(8124, 22)

In [27]:
B

array([[5, 0.5524256651017214, 0, ..., 0, 0, 0.7391304347826086],
       [5, 0.5524256651017214, 9, ..., 0, 0, 0],
       [0, 0.5524256651017214, 0.3076923076923077, ..., 0, 0, 0],
       ...,
       [0, 0.5524256651017214, 0, ..., 0, 0, 0],
       [0, 3, 0, ..., 0.7587939698492462, 0.7049504950495049, 0],
       [5, 0.5524256651017214, 0, ..., 0, 0, 0]], dtype=object)

In [29]:
X.shape

(8124, 22)

In [30]:
B.shape

(8124, 22)

In [31]:
df.shape

(8124, 23)

In [42]:
print(np.unique(df.loc[:,1].values))
print(np.unique(X[:,0]))
print(np.unique(B[:,0]))

['b' 'c' 'f' 'k' 's' 'x']
[0 1 2 3 4 5]
[0 5]


In [41]:
print(np.unique(X[:,0]))

[0 1 2 3 4 5]


In [39]:
s = np.unique([0,1,3,5,2,5,23, 32, 2,2])
print(s)
print(len(s))

[ 0  1  2  3  5 23 32]
7
